### ISSUE TITLE
Attribute causing server kick

### ISSUE THREAD

**Issue by Wizard12892** [Odgug/Vault-Filters#11]
I'm playing on one of Iskall's VH Servers and when I try and make an attribute filter for "is a Jewel item" i get disconnected from the server and my profile stays logged in until the server is restarted.

The disconnect message is "neurina.kick.messageneruina.kick.reason". This happened twice in a row.

Specifics: Using a create:attribute_filter I first added - is in group 'The Vault - Vault Gear' using a vault sword, I then added a Perfect Jewel to add the "is a Jewel item" filter. The attribute is added to the list, in Allow-List (Any) and I hit the checkmark save button. Seconds after hitting the save button I get disconnected from the server with the above error message. 

I was not able to reproduce the issue in my single player world using the same install.

**Comment by Wizard12892** [comment]
UPDATE: Was attempting to make a different attribute filter, this one for "is in group 'The Vault - Vault Gear'" and "is of item ID "Unidentified Treasure Key" and received a kick with the same error. So it might be something with the Vault Gear attribute and a secondary attribute? 

I was able to make an attribute filter for only "is in group 'The Vault - Vault Gear'" with no issues on the server. 
New error was not able to be reproduced in single player either.

**Comment by Wizard12892** [comment]
Update 2: I initially believed that Vault Filters was installed on Iskall's VH servers because the attributes showed up as selectable on the server. However none of the filters that I created using non-vanilla attributes actually function so I no longer believe this to be the case. Seems like the errors occurred because I tried using them when I shouldn't have been.

**Comment by Odgug** [comment]
Ahh yep, this all happend bcz vault filters is not on the iskallia servers, coincidentally an update to prevent this issue from happening is almost done
