### ISSUE TITLE
Filter not working on non unidentified charms

### ISSUE THREAD

**Issue by Zenoo** [Odgug/Vault-Filters#16]
I have a filter for charm items that are not unidentified, yet it's not targeting rolled charms.

Here is the filter

![2024-09-26_00 33 08](https://github.com/user-attachments/assets/70799eb6-d02c-4648-9622-0c7cdcf01cd6)

And it leaves every charm untouched

![2024-09-26_00 34 36](https://github.com/user-attachments/assets/29624a9f-118f-43e7-ae8c-a254817aa7ab)

**Comment by Odgug** [comment]
Are you using vault filters version 1.15.0? If so importers dont work in that version, fixed in 1.15.1

**Comment by Zenoo** [comment]
I'm not sure about the server I'm playing on's version, but other vault filters work in importers. Only this one about the charms

**Comment by Odgug** [comment]
i cant seem to recreate it, i've copied that exact filter and for some reason it isnt working, are you maybe using a charm that was obtained before charms were given a size?

**Comment by Odgug** [comment]
still cant recreate, please confirm that you are on 1.15.1, if you find any more info you can reopen
